#Messages are the fundamental unit of context for models in LangChain. 
#They represent the input and output of models, carrying both the content and metadata needed to represent the state of a conversation 
# when interacting with an LLM.
# a message object have three things Role, Content and Metadata

#  Message types
#  System message - Tells the model how to behave and provide context for interactions
#  Human message - Represents user input and interactions with the model
#  AI message - Responses generated by the model, including text content, tool calls, and metadata
#  Tool message - Represents the outputs of tool calls
from langchain.chat_models import init_chat_model
from dotenv import load_dotenv
from langchain.messages import SystemMessage, HumanMessage
#Load environment variables from .env file
load_dotenv()

#Initialize the chat model
model = init_chat_model("gpt-5.4")

sys_message = SystemMessage(content="You are helful coding assistant.")

human_message = HumanMessage(
    content="What is tuple in python?",
    name="John", #identify user
    id="msg_123"
)

messages = [sys_message, "What is lambda expression in python?"]

print("Name of the human : ",human_message.name)
print("Message Id : ",human_message.id)
response = model.invoke(messages)

print(response.content)

print("Type of model respoinse : ",type(response))